import java.security.MessageDigest

plugins {
    id("megingiard.android.library")
    alias(libs.plugins.kotlin.serialization)
}

// ---------------------------------------------------------------------------
// Generate NativeBinaryHashes.kt by SHA-256-hashing the native injector
// binaries bundled in :app's assets. The generated map is consulted at
// runtime (NativeBinaryInjector.deployBinary) to refuse executing a binary
// that does not match the hash that was committed to the repository.
// ---------------------------------------------------------------------------
abstract class GenerateNativeBinaryHashesTask : DefaultTask() {
    @get:Input
    abstract val nativeBinaryNames: ListProperty<String>

    @get:InputFiles
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val assetFiles: ConfigurableFileCollection

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val md = MessageDigest.getInstance("SHA-256")
        val fileMap = assetFiles.files.associateBy { it.name }
        val entries = nativeBinaryNames.get().joinToString(",\n") { name ->
            val f = fileMap[name]
            checkNotNull(f) { "Missing native binary asset: $name" }
            md.reset()
            val hex = md.digest(f.readBytes())
                .joinToString("") { b -> "%02X".format(b.toInt() and 0xFF) }
            "    \"$name\" to \"$hex\""
        }
        val targetDir = outputDir.get().asFile
            .resolve("com/stormpanda/megingiard/security")
        targetDir.mkdirs()
        targetDir.resolve("NativeBinaryHashes.kt").writeText(
            """// AUTO-GENERATED — do not edit. Regenerated by :domain:generateNativeBinaryHashes.
package com.stormpanda.megingiard.security

/**
 * Expected SHA-256 (uppercase hex) of each native injector binary shipped in
 * `companion/ui/src/main/assets/`. Computed at build time from the committed bytes and
 * checked at runtime in [com.stormpanda.megingiard.input.NativeBinaryInjector]
 * before the binary is made executable.
 */
internal object NativeBinaryHashes {
    val EXPECTED: Map<String, String> = mapOf(
$entries
    )
}
"""
        )
    }
}

val nativeBinaries = listOf(
    "touchinjector_arm64",
    "mouseinjector_arm64",
    "keyinjector_arm64",
    "gamepadinjector_arm64",
    "megingiard_privd_arm64",
    "megingiard_mirror.dex",
)
val assetsDir = rootProject.file("companion/ui/src/main/assets")
val generatedHashesDir = layout.buildDirectory.dir("generated/source/nativeBinaryHashes/kotlin")

val generateNativeBinaryHashes = tasks.register("generateNativeBinaryHashes", GenerateNativeBinaryHashesTask::class.java) {
    dependsOn(":mirrorserver:dex")
    nativeBinaryNames.set(nativeBinaries)
    assetFiles.setFrom(nativeBinaries.map { File(assetsDir, it) })
    outputDir.set(generatedHashesDir)
}

android {
    namespace = "com.stormpanda.megingiard.companion.domain"

    defaultConfig {
        consumerProguardFiles("consumer-rules.pro")
    }

    testOptions {
        unitTests.isReturnDefaultValues = true
    }

    buildFeatures {
        buildConfig = true
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    kotlinOptions {
        // debounce() carries @FlowPreview in the binary metadata of coroutines 1.8.x
        // even though the annotation class is no longer exported publicly.
        // Opt-in globally so no import is needed.
        freeCompilerArgs += "-opt-in=kotlinx.coroutines.FlowPreview"
    }
    sourceSets {
        getByName("main") {
            kotlin.srcDir(generatedHashesDir)
        }
    }
}

// Make every Kotlin compile + KSP-like task depend on the generator.
tasks.matching { it.name.startsWith("compile") && it.name.contains("Kotlin") }.configureEach {
    dependsOn(generateNativeBinaryHashes)
}

dependencies {
    api(project(":shared:core"))
    api(project(":shared:catalog"))
    api(project(":shared:session"))

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.documentfile)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.androidx.datastore.preferences)
    implementation(libs.libadb.android)
    implementation(libs.sun.security.android)
    implementation(libs.conscrypt.android)

    testImplementation(libs.junit)
    testImplementation(libs.robolectric)
    testImplementation(libs.kotlinx.coroutines.test)
}
